framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            api_platform.cache.metadata:
                adapter: cache.adapter.redis
            api_platform.cache.route_name_resolver:
                adapter: cache.adapter.redis
